# Generated by Django 5.2.7 on 2025-10-08 20:36

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skald", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Memo",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("content_length", models.IntegerField()),
                ("metadata", models.JSONField(default=dict)),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("content_hash", models.CharField(max_length=255)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "client_reference_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemoChunk",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chunk_content", models.TextField()),
                ("chunk_index", models.IntegerField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=2048)),
                (
                    "memo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skald.memo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemoChunkKeyword",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("keyword", models.TextField()),
                (
                    "memo_chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skald.memochunk",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemoContent",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "memo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skald.memo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemoRelationship",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("relationship_type", models.TextField()),
                (
                    "memo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skald.memo"
                    ),
                ),
                (
                    "related_memo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skald.memo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemoSummary",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("summary", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=2048)),
                (
                    "memo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skald.memo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemoTag",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tag", models.TextField()),
                (
                    "memo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skald.memo"
                    ),
                ),
            ],
        ),
    ]
