# Generated by Django 5.2.7 on 2025-10-13 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skald", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_project_users",
                to="skald.project",
            ),
        ),
    ]
