# Generated by Django 5.2.7 on 2025-10-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skald", "0002_memo_memochunk_memochunkkeyword_memocontent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memo",
            name="summary",
        ),
    ]
