# Generated by Django 5.2.7 on 2025-10-17 01:26

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skald", "0002_user_current_project"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="memo",
            index=models.Index(
                fields=["project", "client_reference_id"],
                name="skald_memo_project_8101aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="memo",
            index=models.Index(
                fields=["project", "source"], name="skald_memo_project_88bd2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memo",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="skald_memo_metadat_9c96be_gin"
            ),
        ),
    ]
