# Generated by Django 5.2.7 on 2025-10-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skald", "0003_remove_memo_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="pending",
            field=models.BooleanField(default=True),
        ),
    ]
