# Generated by Django 5.2.7 on 2025-10-19 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skald", "0003_memo_skald_memo_project_8101aa_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("memo_operations_limit", models.IntegerField(blank=True, null=True)),
                ("chat_queries_limit", models.IntegerField(blank=True, null=True)),
                ("projects_limit", models.IntegerField(blank=True, null=True)),
                ("features", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["monthly_price"],
            },
        ),
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["stripe_event_id"],
                        name="skald_strip_stripe__efbcc3_idx",
                    ),
                    models.Index(
                        fields=["event_type", "processed"],
                        name="skald_strip_event_t_1ffd58_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("incomplete", "Incomplete"),
                            ("incomplete_expired", "Incomplete Expired"),
                            ("trialing", "Trialing"),
                            ("unpaid", "Unpaid"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("trial_start", models.DateTimeField(blank=True, null=True)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="skald.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="skald.plan",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["stripe_customer_id"],
                        name="skald_organ_stripe__787c7f_idx",
                    ),
                    models.Index(
                        fields=["stripe_subscription_id"],
                        name="skald_organ_stripe__4bbed4_idx",
                    ),
                    models.Index(
                        fields=["status"], name="skald_organ_status_b30bd1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_period_start", models.DateField()),
                ("billing_period_end", models.DateField()),
                ("memo_operations_count", models.IntegerField(default=0)),
                ("chat_queries_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="skald.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-billing_period_start"],
                "indexes": [
                    models.Index(
                        fields=["organization", "billing_period_start"],
                        name="skald_usage_organiz_41ff84_idx",
                    ),
                    models.Index(
                        fields=["billing_period_start"],
                        name="skald_usage_billing_07f781_idx",
                    ),
                ],
                "unique_together": {("organization", "billing_period_start")},
            },
        ),
    ]
