# Generated by Django 5.2.7 on 2025-10-10 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skald", "0004_memo_pending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memorelationship",
            name="memo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships_from",
                to="skald.memo",
            ),
        ),
        migrations.AlterField(
            model_name="memorelationship",
            name="related_memo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships_to",
                to="skald.memo",
            ),
        ),
    ]
