# Generated by Django 5.2.7 on 2025-10-20 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skald", "0004_subscription_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsubscription",
            name="scheduled_change_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when the scheduled plan change will take effect",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organizationsubscription",
            name="scheduled_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan scheduled to take effect at the end of the current period",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_subscriptions",
                to="skald.plan",
            ),
        ),
        migrations.AddField(
            model_name="organizationsubscription",
            name="stripe_schedule_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="organizationsubscription",
            index=models.Index(
                fields=["stripe_schedule_id"], name="skald_organ_stripe__fb7b46_idx"
            ),
        ),
    ]
