# Generated by Django 5.2.7 on 2025-10-20 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skald", "0005_add_scheduled_plan_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagerecord",
            name="alerts_sent",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="organizationsubscription",
            name="scheduled_change_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organizationsubscription",
            name="scheduled_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_subscriptions",
                to="skald.plan",
            ),
        ),
    ]
