# Generated by Django 5.2.7 on 2025-10-30 11:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skald", "0006_usage_alerts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessageGroup",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_query", models.TextField()),
                ("model_response", models.TextField()),
                ("context_str", models.TextField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skald.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skald.project"
                    ),
                ),
            ],
        ),
    ]
