# Generated by Django 5.2.7 on 2025-10-13 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skald", "0007_project_memo_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectApiKey",
            fields=[
                (
                    "api_key_hash",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("first_12_digits", models.CharField(max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skald.project"
                    ),
                ),
            ],
        ),
    ]
