# fly.toml app configuration file generated for skald-server on 2025-06-10T18:36:47-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'skald-api'
primary_region = 'dfw'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'
  FRONTEND_URL = 'https://platform.useskald.com'
  POSTHOG_HOST = 'https://us.i.posthog.com'
  POSTHOG_PUBLIC_API_KEY = 'phc_B77mcYC1EycR6bKLgSNzjM9aaeiWXhoeizyriFIxWf2'
  APP_LOG_LEVEL = 'DEBUG'
  LANGSMITH_TRACING='true'
  SQS_QUEUE_URL='https://sqs.us-east-2.amazonaws.com/295993620487/SkaldMemoProcessingQueue'
  LANGSMITH_ENDPOINT='https://api.smith.langchain.com'
  LANGSMITH_PROJECT='pr-abandoned-corporatism-94'


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  interval = "10s"
  grace_period = "60s"
  method = "GET"
  path = "/api/health"
  protocol = "http"
  port = 8000
  timeout = "10s"
  tls_skip_verify = false

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4

# [[statics]]
#   guest_path = '/code/static'
#   url_prefix = '/static/'
