app = 'skald-platform-ui'
primary_region = 'dfw'

[build]
  dockerfile = "ui.Dockerfile"
  [build.args]
    VITE_API_HOST = "https://api.useskald.com"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1