# fly.toml app configuration file generated for skald-backend on 2025-10-31T00:00:00-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'skald-backend'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

[env]
  LANGSMITH_ENDPOINT = 'https://api.smith.langchain.com'
  LANGSMITH_TRACING = 'true'
  NODE_ENV = 'production'
  INTER_PROCESS_QUEUE = 'sqs'
  EXPRESS_SERVER_PORT = 8080

[processes]
  api = 'node dist/index.js --mode=express-server'
  memo-processing-server = 'node dist/index.js --mode=memo-processing-server'

[http_service]
  processes = ['api']
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 1

[[vm]]
  processes = ['api']
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2

[[vm]]
  processes = ['memo-processing-server']
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
