CREATE TABLE skald_organizationsubscription (
    id bigint NOT NULL,
    stripe_customer_id character varying(255),
    stripe_subscription_id character varying(255),
    status character varying(50) NOT NULL,
    current_period_start timestamp with time zone NOT NULL,
    current_period_end timestamp with time zone NOT NULL,
    cancel_at_period_end boolean NOT NULL,
    canceled_at timestamp with time zone,
    trial_start timestamp with time zone,
    trial_end timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organization_id uuid NOT NULL,
    plan_id bigint NOT NULL,
    scheduled_change_date timestamp with time zone,
    scheduled_plan_id bigint,
    stripe_schedule_id character varying(255),
    PRIMARY KEY (id)
);