name: Tests

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'
  pull_request:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345678
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_USER: postgres
      DB_PASSWORD: 12345678
      DB_HOST: localhost
      DB_PORT: 5432
      TEST_DB_NAME: skald2_test
      INTER_PROCESS_QUEUE: 'redis'

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run tests
        run: ./bin/test.sh
